# Generated by Django 5.0.7 on 2024-08-15 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_remove_actuador_usuarios_remove_empresa_usuarios_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariovai',
            name='actuadores',
            field=models.ManyToManyField(related_name='usuarios', to='plantas.actuador'),
        ),
        migrations.AddField(
            model_name='usuariovai',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='plantas.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariovai',
            name='estaciones',
            field=models.ManyToManyField(related_name='usuarios', to='plantas.estacion'),
        ),
        migrations.AddField(
            model_name='usuariovai',
            name='plantas',
            field=models.ManyToManyField(related_name='usuarios', to='plantas.planta'),
        ),
        migrations.AddField(
            model_name='usuariovai',
            name='sensores',
            field=models.ManyToManyField(related_name='usuarios', to='plantas.sensor'),
        ),
    ]
