# Generated by Django 5.0.7 on 2024-08-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuador',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='usuarios',
        ),
        migrations.AlterField(
            model_name='actuador',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
