# Generated by Django 5.0.7 on 2024-08-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_remove_actuador_usuarios_remove_empresa_usuarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuador',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='codigo_barras',
        ),
        migrations.AddField(
            model_name='actuador',
            name='codigo_qr',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='codigo_qr',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='modeloe',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='codigo_qr',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='actuador',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actuadores', to='plantas.estacion'),
        ),
        migrations.AlterField(
            model_name='datosactuador',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos_actuadores', to='plantas.planta'),
        ),
        migrations.AlterField(
            model_name='datossensor',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos_sensores', to='plantas.planta'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='plantas.planta'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='estacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='plantas.estacion'),
        ),
    ]
