# Generated by Django 5.0.7 on 2024-08-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_remove_actuador_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuador',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='actuador',
            name='en_uso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='en_uso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actuador',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuadores', to='plantas.tiposensor'),
        ),
        migrations.AlterField(
            model_name='modeloe',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
