# Generated by Django 5.0.7 on 2024-08-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0004_actuador_descripcion_actuador_en_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(default='Estacion sin nombre', max_length=100),
            preserve_default=False,
        ),
    ]
