# Generated by Django 5.0.7 on 2024-08-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0005_estacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
